import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "WiztecBD",
  description: "Generated by WiztecBD",
  metadataBase: new URL("https://wiztech-six.vercel.app"),
  openGraph: {
    title: "WiztecBD",
    description: "Generated by WiztecBD",
    url: "https://wiztech-six.vercel.app",
    siteName: "WiztecBD",
    images: [
      {
        url: "/icons/common/logo.svg",
        width: 800,
        height: 600,
        alt: "WiztecBD Logo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "WiztecBD",
    description: "Generated by WiztecBD",
    images: ["/icons/common/logo.svg"],
    creator: "@wiztecbd",
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
