import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import "keen-slider/keen-slider.min.css";
import "@smastrom/react-rating/style.css";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "WiztecBD",
  description: "Generated by WiztecBD",
  metadataBase: new URL("https://wiztech-six.vercel.app"),
  openGraph: {
    title: "WiztecBD",
    description: "Generated by WiztecBD",
    url: "https://wiztech-six.vercel.app",
    siteName: "WiztecBD",
    images: [
      {
        url: "https://i.ibb.co.com/HTpQydGd/Frame-9.png",
        width: 800,
        height: 600,
        alt: "WiztecBD Logo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "WiztecBD",
    description: "Generated by WiztecBD",
    images: ["https://i.ibb.co.com/HTpQydGd/Frame-9.png"],
    creator: "@wiztecbd",
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pb-12 lg:pb-0">
        <Navbar />
        <div className=""> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
